/**
 * chapters-data.js — 完整 C# 入门到面向对象闯关课程
 * 6 大阶段 · 13 章 · 34 关
 * 从零基础小白到能独立编写小型控制台项目
 * 所有关卡均经 runner.js 模拟执行验证通过
 */
const CHAPTERS_DATA = [
    // ============ 阶段 1：入门基础 ============
    {
        stage: '入门基础', stageDesc: '从零开始，认识 C# 的世界',
        chapters: [
            { id:1, title:'第 1 章：初识 C#', desc:'了解 C# 是什么，写出第一行代码', lessons: [
                { id:'c1l1', title:'Hello World', content:`<h3>C# 是什么</h3><p>C#（读作 "See Sharp"）是微软出的现代编程语言，语法清晰，用途广：桌面软件、网站、手机 App、游戏（Unity 引擎首选）。学它，能做的东西很多。</p><h3>程序的最小骨架</h3><p>每个 C# 程序都从一个叫 <code>Main</code> 的方法开始跑。先记住这个模板，后续关卡都长这样：</p><pre><code>using System;              // 引入系统库，才能用 Console\n\nclass Program              // 定义一个类\n{\n    static void Main()     // 程序入口\n    {\n        Console.WriteLine("Hello, C#!");  // 输出一行\n    }\n}</code></pre><h3>两个输出方法</h3><ul><li><code>Console.WriteLine()</code> — 输出后<strong>换行</strong></li><li><code>Console.Write()</code> — 输出后<strong>不换行</strong></li></ul><p>每条语句必须以分号 <code>;</code> 结尾，这是 C# 的"句号"。</p><h3>任务</h3><p>修改代码，让程序<strong>分两行</strong>输出：</p><pre><code>Hello, C#!\nI am learning.</code></pre>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Console.WriteLine("Hello, World!");\n    }\n}`, expectedOutput:'Hello, C#!\nI am learning.', hint:'使用两次 Console.WriteLine()，分别输出一行。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Console.WriteLine("Hello, C#!");\n        Console.WriteLine("I am learning.");\n    }\n}` },
                { id:'c1l2', title:'注释与代码规范', content:`<h3>注释是什么</h3><p>注释是写给<strong>人看</strong>的说明，计算机执行时会完全忽略。写注释是优秀程序员的基本习惯——不是写给自己看，是写给三个月后的自己和同事看。</p><h3>两种写法</h3><pre><code>// 单行注释，从 // 到行末都是说明\n\n/*\n   多行注释\n   适合写详细说明或临时屏蔽一段代码\n*/</code></pre><h3>什么时候写</h3><ul><li>解释<strong>为什么</strong>这么做（而不是做了什么）</li><li>标记暂时不用的代码</li><li>给复杂逻辑加说明</li></ul><h3>任务</h3><p>给下面的代码加一行注释，输出保持不变：</p><pre><code>Learning C#</code></pre>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Console.WriteLine("Learning C#");\n    }\n}`, expectedOutput:'Learning C#', hint:'在代码上方用 // 加说明即可。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        // 输出一句话\n        Console.WriteLine("Learning C#");\n    }\n}` },
                { id:'c1l3', title:'输入与输出', content:`<h3>读取用户输入</h3><p>真实程序不是只往外输出，还要<strong>接收用户输入</strong>。<code>Console.ReadLine()</code> 会停下来等用户输入一行文字，按回车后把那行文字作为字符串返回。</p><pre><code>Console.Write("请输入名字：");      // 先提示\nstring name = Console.ReadLine();   // 读取输入\nConsole.WriteLine("你好，" + name);  // 再输出</code></pre><p>本平台支持输入：当代码里有 <code>Console.ReadLine()</code>，运行前会弹出输入框让你填写。</p><h3>任务</h3><p>读取一行输入，然后输出 <strong>你输入的是：xxx</strong>（xxx 是用户输入的内容）。测试时输入"测试"，预期输出：</p><pre><code>你输入的是：测试</code></pre>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        // 读取输入并输出\n    }\n}`, expectedOutput:'你输入的是：测试', hint:'用 string s = Console.ReadLine(); 读取，然后 Console.WriteLine 输出。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        string s = Console.ReadLine();\n        Console.WriteLine("你输入的是：" + s);\n    }\n}` }
            ]},
            { id:2, title:'第 2 章：变量与数据类型', desc:'学会存储和使用不同类型的数据', lessons: [
                { id:'c2l1', title:'变量声明', content:`<h3>变量：有名字的盒子</h3><p>变量用来<strong>存数据</strong>。你可以把它想象成一个贴了标签的盒子，标签是变量名，盒子里装的是数据。用之前必须先声明：告诉计算机这个盒子存什么类型。</p><h3>五种基本类型</h3><ul><li><code>int</code> — 整数（18、-5、2024）</li><li><code>double</code> — 小数（3.14、-0.5）</li><li><code>string</code> — 文本，用双引号（"你好"）</li><li><code>bool</code> — 真假，只有 <code>true</code> / <code>false</code></li><li><code>char</code> — 单个字符，用单引号（'A'、'中'）</li></ul><pre><code>int age = 18;            // 整数\nstring name = "小明";     // 字符串\ndouble price = 9.9;      // 小数\nbool isStudent = true;   // 布尔值\nchar grade = 'A';        // 单字符</code></pre><h3>任务</h3><p>创建三个变量，分别输出三行：</p><pre><code>我叫小明\n今年18岁\n来自北京</code></pre>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        // 创建变量并输出\n    }\n}`, expectedOutput:'我叫小明\n今年18岁\n来自北京', hint:'string 存名字和城市，int 存年龄。用 + 拼接字符串。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        string name = "小明";\n        int age = 18;\n        string city = "北京";\n        Console.WriteLine("我叫" + name);\n        Console.WriteLine("今年" + age + "岁");\n        Console.WriteLine("来自" + city);\n    }\n}` },
                { id:'c2l2', title:'字符串插值', content:`<h3>字符串插值：优雅地拼字符串</h3><p>用 <code>+</code> 拼接变量和字符串很啰嗦：<code>"我叫" + name + "，今年" + age + "岁"</code>。C# 6.0 引入了<strong>字符串插值</strong>，写起来清爽得多：</p><pre><code>string name = "小明";\nint age = 18;\n// 旧方式：一堆引号和加号\nConsole.WriteLine("我叫" + name + "，今年" + age + "岁");\n// 新方式：在字符串前加 $，变量用 {} 包起来\nConsole.WriteLine($"我叫{name}，今年{age}岁");</code></pre><p>规则：字符串前面加 <code>$</code>，用 <code>{变量名}</code> 把变量嵌进去。{} 里甚至可以写表达式，如 <code>{age + 1}</code>。</p><h3>任务</h3><p>用字符串插值输出三行：</p><pre><code>商品：苹果\n价格：5.5 元\n库存：100 个</code></pre>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        string product = "苹果";\n        double price = 5.5;\n        int stock = 100;\n        // 用插值输出\n    }\n}`, expectedOutput:'商品：苹果\n价格：5.5 元\n库存：100 个', hint:'字符串前加 $，变量用 {变量名} 嵌入。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        string product = "苹果";\n        double price = 5.5;\n        int stock = 100;\n        Console.WriteLine($"商品：{product}");\n        Console.WriteLine($"价格：{price} 元");\n        Console.WriteLine($"库存：{stock} 个");\n    }\n}` },
                { id:'c2l3', title:'类型转换', content:`<h3>为什么要类型转换</h3><p>不同类型不能随便混用。比如从输入读到的永远是 string，要做数学计算就得先转成数字；反过来，数字要拼进句子也得转成 string。</p><h3>三种常见转换</h3><pre><code>// 1. 自动转换：小类型 → 大类型，不丢数据\nint i = 10;\ndouble d = i;            // int 自动变 double，d = 10.0\n\n// 2. 强制转换：大类型 → 小类型，可能丢精度\ndouble pi = 3.14;\nint n = (int)pi;         // n = 3，小数部分直接截断\n\n// 3. 字符串 ↔ 数字\nstring s = "42";\nint num = int.Parse(s);  // 字符串 → 整数\nint x = 99;\nstring text = x.ToString();  // 整数 → 字符串</code></pre><h3>任务</h3><p>把字符串 <code>"123"</code> 转成整数，加 77，输出结果 <strong>200</strong></p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        string s = "123";\n        // 转换并计算\n    }\n}`, expectedOutput:'200', hint:'用 int.Parse(s) 转成数字，再 +77。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        string s = "123";\n        int num = int.Parse(s);\n        Console.WriteLine(num + 77);\n    }\n}` },
                { id:'c2l4', title:'常量与 var', content:`<h3>常量 const：不能改的变量</h3><p>有些值一旦定下就不该被改，比如一天 24 小时、圆周率。用 <code>const</code> 声明后，再给它赋值会直接报错——这是给代码加"保险"。</p><pre><code>const double Pi = 3.14159;\n// Pi = 3;  // ❌ 编译错误！常量不能重新赋值</code></pre><p>习惯：常量名用大写，便于一眼识别。</p><h3>隐式类型 var：让编译器猜</h3><p>声明变量时写 <code>var</code>，编译器会根据右边的值自动推断类型，写起来更省事：</p><pre><code>var name = "小明";    // 编译器推断为 string\nvar age = 18;         // 推断为 int\nvar price = 9.9;      // 推断为 double</code></pre><p>注意：<code>var</code> 只是省事，类型一旦推断出来就固定了，不是"随便什么类型都行"。</p><h3>任务</h3><p>定义常量 <code>HoursPerDay = 24</code>，计算 7 天共有多少小时，输出 <strong>168</strong></p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        // 定义常量并计算\n    }\n}`, expectedOutput:'168', hint:'const int HoursPerDay = 24; 输出 HoursPerDay * 7。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        const int HoursPerDay = 24;\n        Console.WriteLine(HoursPerDay * 7);\n    }\n}` }
            ]},
            { id:3, title:'第 3 章：运算符', desc:'算术、比较、逻辑运算', lessons: [
                { id:'c3l1', title:'算术运算', content:`<h3>算术运算符</h3><ul><li><code>+ - * /</code> — 加、减、乘、除</li><li><code>%</code> — 取余数（10 % 3 = 1）</li><li><code>++ --</code> — 自增自减（<code>i++</code> 等于 <code>i = i + 1</code>）</li></ul><pre><code>int a = 10, b = 3;\nConsole.WriteLine(a + b);  // 13\nConsole.WriteLine(a / b);  // 3（整数除法）\nConsole.WriteLine(a % b);  // 1（10 除以 3 余 1）</code></pre><p>⚠️ <strong>关键陷阱</strong>：<code>int / int</code> 结果还是 int，小数部分直接丢掉（不是四舍五入）。<code>10 / 3</code> 得 3，不是 3.33。要小数结果，至少有一个数得是 double：<code>10.0 / 3</code> 得 3.33...</p><h3>任务</h3><p>计算 100 除以 7 的<strong>商</strong>和<strong>余数</strong>：</p><pre><code>商：14\n余数：2</code></pre>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int a = 100, b = 7;\n        // 计算\n    }\n}`, expectedOutput:'商：14\n余数：2', hint:'商是 a / b，余数是 a % b。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int a = 100, b = 7;\n        Console.WriteLine($"商：{a / b}");\n        Console.WriteLine($"余数：{a % b}");\n    }\n}` },
                { id:'c3l2', title:'比较与逻辑运算', content:`<h3>比较运算符</h3><p>比较两个值的大小关系，结果是 <code>bool</code>（true 或 false）：</p><ul><li><code>==</code> 等于 · <code>!=</code> 不等于</li><li><code>&gt;</code> 大于 · <code>&lt;</code> 小于</li><li><code>&gt;=</code> 大于等于 · <code>&lt;=</code> 小于等于</li></ul><h3>逻辑运算符</h3><p>把多个 bool 条件组合起来：</p><ul><li><code>&amp;&amp;</code> 与 — <strong>两个都真</strong>才真</li><li><code>||</code> 或 — <strong>一个真</strong>就真</li><li><code>!</code> 非 — 真变假，假变真</li></ul><pre><code>int age = 20;\nbool isAdult = age &gt;= 18;          // true\nbool canVote = isAdult &amp;&amp; true;    // true\nbool isTeen = age &gt;= 13 &amp;&amp; age &lt; 20; // false</code></pre><h3>任务</h3><p>判断 score=85 是否"<strong>既及格（≥60）又不是满分（&lt;100）</strong>"，输出 <strong>True</strong></p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int score = 85;\n        // 写判断\n    }\n}`, expectedOutput:'True', hint:'用 && 连接两个比较：score >= 60 && score < 100。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int score = 85;\n        Console.WriteLine(score >= 60 && score < 100);\n    }\n}` }
            ]}
        ]
    },
    // ============ 阶段 2：控制流 ============
    {
        stage: '控制流', stageDesc: '让程序学会判断和重复',
        chapters: [
            { id:4, title:'第 4 章：条件判断', desc:'if / else / switch', lessons: [
                { id:'c4l1', title:'if-else 判断', content:`<h3>让程序做选择</h3><p>程序最基本的能力就是<strong>根据条件做不同的事</strong>。<code>if-else</code> 是实现这个能力的语法。</p><pre><code>int score = 85;\nif (score &gt;= 90)\n    Console.WriteLine("优秀");\nelse if (score &gt;= 60)\n    Console.WriteLine("及格");\nelse\n    Console.WriteLine("不及格");</code></pre><p>执行流程：从上往下挨个检查条件，<strong>遇到第一个满足的就执行对应代码，然后跳出整个 if 结构</strong>。一个都不满足就执行 <code>else</code>。</p><h3>任务</h3><p>判断温度 temp=18 该穿什么：</p><ul><li>&lt; 10：穿棉衣</li><li>10~25：穿长袖</li><li>≥ 25：穿短袖</li></ul><p>输出 <strong>穿长袖</strong></p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int temp = 18;\n        // 写判断\n    }\n}`, expectedOutput:'穿长袖', hint:'先 if (temp < 10)，再 else if (temp < 25)，最后 else。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int temp = 18;\n        if (temp < 10)\n            Console.WriteLine("穿棉衣");\n        else if (temp < 25)\n            Console.WriteLine("穿长袖");\n        else\n            Console.WriteLine("穿短袖");\n    }\n}` },
                { id:'c4l2', title:'switch 多分支', content:`<h3>switch：等值匹配的利器</h3><p>当判断条件是"<strong>等于某个值</strong>"时，写一长串 <code>if-else if</code> 很啰嗦，<code>switch</code> 更清晰：</p><pre><code>int day = 3;\nswitch (day)\n{\n    case 1: Console.WriteLine("周一"); break;\n    case 2: Console.WriteLine("周二"); break;\n    case 3: Console.WriteLine("周三"); break;\n    default: Console.WriteLine("其他"); break;\n}</code></pre><p>要点：每个 <code>case</code> 后面必须有 <code>break</code>（否则会继续执行下一个 case）；<code>default</code> 处理所有没匹配到的情况，相当于 else。</p><h3>任务</h3><p>用 switch 根据运算符 <code>op="*"</code> 输出对应的中文运算名，输出 <strong>乘法</strong></p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        string op = "*";\n        // switch\n    }\n}`, expectedOutput:'乘法', hint:'switch (op) { case "*": Console.WriteLine("乘法"); break; }', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        string op = "*";\n        switch (op)\n        {\n            case "+": Console.WriteLine("加法"); break;\n            case "-": Console.WriteLine("减法"); break;\n            case "*": Console.WriteLine("乘法"); break;\n            case "/": Console.WriteLine("除法"); break;\n        }\n    }\n}` },
                { id:'c4l3', title:'三元运算符', content:`<h3>三元运算符：一行写 if-else</h3><p>当你只需要根据条件<strong>选一个值</strong>时，用 <code>? :</code> 一行搞定，比 if-else 简洁：</p><pre><code>int age = 20;\nstring status = age &gt;= 18 ? "成年" : "未成年";\n// 等价于：\n// string status;\n// if (age &gt;= 18) status = "成年";\n// else status = "未成年";</code></pre><p>格式：<code>条件 ? 真时的值 : 假时的值</code>。适合简单的二选一，逻辑复杂时还是用 if-else 更易读。</p><h3>任务</h3><p>判断 num=7 是奇数还是偶数，输出 <strong>奇数</strong></p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int num = 7;\n        // 三元\n    }\n}`, expectedOutput:'奇数', hint:'num % 2 == 0 ? "偶数" : "奇数"。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int num = 7;\n        Console.WriteLine(num % 2 == 0 ? "偶数" : "奇数");\n    }\n}` }
            ]},
            { id:5, title:'第 5 章：循环', desc:'for / while / foreach', lessons: [
                { id:'c5l1', title:'for 循环', content:`<h3>for 循环：重复执行</h3><p>需要<strong>重复做某件事</strong>时用循环。<code>for</code> 是最常用的循环，适合"已知次数"的场景：</p><pre><code>for (int i = 1; i &lt;= 5; i++)\n{\n    Console.WriteLine(i);\n}\n// 输出 1 2 3 4 5</code></pre><h3>三个组成部分</h3><ul><li><code>int i = 1</code> — 初始化：循环变量从 1 开始</li><li><code>i &lt;= 5</code> — 条件：只要 i ≤ 5 就继续，否则结束</li><li><code>i++</code> — 每轮结束后 i 加 1</li></ul><p>执行顺序：初始化 → 检查条件 → 执行循环体 → i++ → 再检查条件 → ...</p><h3>任务</h3><p>输出 1 到 10 每个数的平方：</p><pre><code>1 的平方是 1\n2 的平方是 4\n...\n10 的平方是 100</code></pre>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        // 写循环\n    }\n}`, expectedOutput:'1 的平方是 1\n2 的平方是 4\n3 的平方是 9\n4 的平方是 16\n5 的平方是 25\n6 的平方是 36\n7 的平方是 49\n8 的平方是 64\n9 的平方是 81\n10 的平方是 100', hint:'for i = 1; i <= 10; i++，平方是 i * i。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        for (int i = 1; i <= 10; i++)\n        {\n            Console.WriteLine($"{i} 的平方是 {i * i}");\n        }\n    }\n}` },
                { id:'c5l2', title:'while 循环', content:`<h3>while 循环：不确定次数时用</h3><p><code>while</code> 只有一个条件，<strong>条件为真就一直执行</strong>。适合"不知道要循环多少次"的场景：</p><pre><code>int n = 1;\nwhile (n &lt;= 100)\n{\n    Console.WriteLine(n);\n    n *= 2;  // n 每次翻倍\n}\n// 输出 1 2 4 8 16 32 64</code></pre><p>⚠️ <strong>必须保证条件最终会变假</strong>，否则会变成死循环，程序卡死。<code>n *= 2</code> 让 n 不断变大，最终超过 100 退出。</p><p>for 和 while 可以互相转换：知道次数用 for 更清晰，不知道次数用 while。</p><h3>任务</h3><p>用 while 求 1 加到 100 的和，输出 <strong>5050</strong></p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        // while 累加\n    }\n}`, expectedOutput:'5050', hint:'int sum=0, i=1; while (i<=100) { sum+=i; i++; }', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int sum = 0, i = 1;\n        while (i <= 100)\n        {\n            sum += i;\n            i++;\n        }\n        Console.WriteLine(sum);\n    }\n}` },
                { id:'c5l3', title:'嵌套循环', content:`<h3>嵌套循环：循环里套循环</h3><p>外层循环每执行<strong>一次</strong>，内层循环<strong>完整跑一轮</strong>。这是处理表格、矩阵、乘法表等二维数据的常用方式。</p><pre><code>for (int i = 1; i &lt;= 3; i++)       // 外层 3 次\n{\n    for (int j = 1; j &lt;= 3; j++)   // 内层每次 3 次\n    {\n        Console.Write($"{i}*{j}={i*j} ");\n    }\n    Console.WriteLine();           // 每行结束换行\n}</code></pre><p>总执行次数 = 外层次数 × 内层次数。上面共 3×3=9 次。</p><h3>任务</h3><p>输出九九乘法表<strong>前 3 行</strong>：</p><pre><code>1*1=1\n2*1=2 2*2=4\n3*1=3 3*2=6 3*3=9</code></pre>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        // 嵌套循环\n    }\n}`, expectedOutput:'1*1=1\n2*1=2 2*2=4\n3*1=3 3*2=6 3*3=9', hint:'外层 i 从 1 到 3，内层 j 从 1 到 i。用 Console.Write 不换行。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        for (int i = 1; i <= 3; i++)\n        {\n            for (int j = 1; j <= i; j++)\n            {\n                Console.Write($"{i}*{j}={i*j}");\n                if (j < i) Console.Write(" ");\n            }\n            Console.WriteLine();\n        }\n    }\n}` },
                { id:'c5l4', title:'break 与 continue', content:`<h3>控制循环的执行</h3><ul><li><code>break</code> — 立刻<strong>跳出整个循环</strong>，不再继续</li><li><code>continue</code> — 跳过<strong>本次</strong>剩余代码，直接进入下一轮</li></ul><pre><code>for (int i = 1; i &lt;= 10; i++)\n{\n    if (i == 5) break;        // 遇到 5 整个循环结束\n    if (i % 2 == 0) continue; // 跳过偶数，不输出\n    Console.WriteLine(i);\n}\n// 输出 1 3（到 5 就 break 了，4 没机会输出）</code></pre><h3>任务</h3><p>输出 1~20 内所有 3 的倍数，但<strong>遇到 15 就停止</strong>：</p><pre><code>3\n6\n9\n12</code></pre>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        // 循环 + break\n    }\n}`, expectedOutput:'3\n6\n9\n12', hint:'for i 1~20，if (i == 15) break; if (i % 3 == 0) 输出。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        for (int i = 1; i <= 20; i++)\n        {\n            if (i == 15) break;\n            if (i % 3 == 0) Console.WriteLine(i);\n        }\n    }\n}` }
            ]}
        ]
    },
    // ============ 阶段 3：数据结构 ============
    {
        stage: '数据结构', stageDesc: '数组、字符串、集合',
        chapters: [
            { id:6, title:'第 6 章：数组', desc:'一次存储多个数据', lessons: [
                { id:'c6l1', title:'数组基础', content:`<h3>数组：一次存多个数据</h3><p>数组是<strong>一组相同类型数据的集合</strong>，用下标访问每个元素。下标从 <strong>0</strong> 开始（不是 1！）。</p><pre><code>int[] nums = { 10, 20, 30, 40 };\nConsole.WriteLine(nums[0]);      // 10（第 1 个）\nConsole.WriteLine(nums[2]);      // 30（第 3 个）\nConsole.WriteLine(nums.Length);  // 4（元素个数）</code></pre><p>⚠️ 下标从 0 开始：4 个元素的数组，下标是 0、1、2、3，<code>nums[4]</code> 会越界报错。</p><p>遍历数组用 <code>foreach</code> 最省事：<code>foreach (int n in nums) { ... }</code>，不用管下标。</p><h3>任务</h3><p>给定数组 { 5, 12, 8, 21, 3 }，输出所有元素之和 <strong>49</strong></p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int[] nums = { 5, 12, 8, 21, 3 };\n        int sum = 0;\n        // 累加\n        Console.WriteLine(sum);\n    }\n}`, expectedOutput:'49', hint:'foreach (int n in nums) sum += n;', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int[] nums = { 5, 12, 8, 21, 3 };\n        int sum = 0;\n        foreach (int n in nums) sum += n;\n        Console.WriteLine(sum);\n    }\n}` },
                { id:'c6l2', title:'找最大值与最小值', content:`<h3>找最大值的思路</h3><p>经典算法：<strong>假设第一个元素是最大值，然后逐个比较，遇到更大的就更新</strong>。一轮比较下来，留下的就是真正的最大值。</p><pre><code>int[] nums = { 3, 9, 2, 7 };\nint max = nums[0];           // 先假设第 1 个最大\nforeach (int n in nums)\n{\n    if (n &gt; max) max = n;    // 发现更大的就更新\n}\n// max = 9</code></pre><p>找最小值同理，只是把 <code>&gt;</code> 换成 <code>&lt;</code>，初始值设为 <code>nums[0]</code>。</p><h3>任务</h3><p>找出数组 { 12, 45, 7, 89, 23, 56 } 的最大值，输出 <strong>89</strong></p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int[] nums = { 12, 45, 7, 89, 23, 56 };\n        // 找最大\n    }\n}`, expectedOutput:'89', hint:'设 max = nums[0]，foreach 中比较更新。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int[] nums = { 12, 45, 7, 89, 23, 56 };\n        int max = nums[0];\n        foreach (int n in nums)\n            if (n > max) max = n;\n        Console.WriteLine(max);\n    }\n}` },
                { id:'c6l3', title:'数组反转', content:`<h3>反转数组</h3><p>最直观的做法：<strong>从最后一个元素开始，往前遍历输出</strong>。最后一个元素的下标是 <code>Length - 1</code>（因为下标从 0 开始）。</p><pre><code>int[] nums = { 1, 2, 3, 4, 5 };\n// 正序：1 2 3 4 5\n// 反序：从 nums.Length-1 (=4) 到 0\nfor (int i = nums.Length - 1; i &gt;= 0; i--)\n{\n    Console.Write(nums[i] + " ");\n}\n// 输出 5 4 3 2 1</code></pre><h3>任务</h3><p>把数组 { 1, 2, 3, 4, 5 } 反转后输出（空格分隔）：</p><pre><code>5 4 3 2 1</code></pre>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int[] nums = { 1, 2, 3, 4, 5 };\n        // 反转并输出\n    }\n}`, expectedOutput:'5 4 3 2 1', hint:'从 nums.Length-1 到 0 倒着遍历。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int[] nums = { 1, 2, 3, 4, 5 };
        for (int i = nums.Length - 1; i >= 0; i--)
        {
            Console.Write(nums[i]);
            if (i > 0) Console.Write(" ");
        }
    }
}` },
            ]},
            { id:7, title:'第 7 章：字符串', desc:'文本处理的利器', lessons: [
                { id:'c7l1', title:'字符串常用属性', content:`<h3>字符串的属性与拼接</h3><p><code>string</code> 是文本类型，有两个常用操作：</p><ul><li><code>.Length</code> — 获取字符个数（属性，不加括号）</li><li><code>+</code> — 拼接两个字符串</li></ul><pre><code>string s = "Hello";\nConsole.WriteLine(s.Length);     // 5\nConsole.WriteLine(s + " World"); // Hello World</code></pre><p>注意：<code>Length</code> 是属性不是方法，写 <code>s.Length</code> 不写 <code>s.Length()</code>。拼接也可以用插值 <code>$"{s} World"</code>，更优雅。</p><h3>任务</h3><p>给定 str="Programming"，输出它的长度 <strong>11</strong></p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        string str = "Programming";\n        // 输出长度\n    }\n}`, expectedOutput:'11', hint:'Console.WriteLine(str.Length);', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        string str = "Programming";\n        Console.WriteLine(str.Length);\n    }\n}` },
                { id:'c7l2', title:'字符串方法', content:`<h3>字符串常用方法</h3><p>字符串自带很多实用方法（方法要加括号调用）：</p><pre><code>string s = "Hello World";\nConsole.WriteLine(s.ToUpper());            // HELLO WORLD\nConsole.WriteLine(s.ToLower());            // hello world\nConsole.WriteLine(s.Substring(0, 5));      // Hello\nConsole.WriteLine(s.Replace("World", "C#")); // Hello C#\nConsole.WriteLine(s.Contains("World"));    // True</code></pre><p>方法可以<strong>链式调用</strong>：<code>s.ToUpper().Replace("WORLD","C#")</code> 先转大写再替换，从左到右依次执行。</p><h3>任务</h3><p>把 "Hello World" 先转大写，再替换 "WORLD" 为 "C#"，输出 <strong>HELLO C#</strong></p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        string s = "Hello World";\n        // 转换\n    }\n}`, expectedOutput:'HELLO C#', hint:'先 ToUpper()，再 Replace("WORLD", "C#")。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        string s = "Hello World";\n        string result = s.ToUpper().Replace("WORLD", "C#");\n        Console.WriteLine(result);\n    }\n}` },
                { id:'c7l3', title:'字符串分割与拼接', content:`<h3>Split 与 Join：拆分与拼接</h3><p>处理 CSV、URL 等结构化文本的利器：</p><pre><code>// Split：按分隔符拆成数组\nstring csv = "苹果,香蕉,橘子";\nstring[] fruits = csv.Split(',');\n// fruits = ["苹果", "香蕉", "橘子"]\n\n// Join：用分隔符把数组连成字符串\nstring joined = string.Join(" | ", fruits);\n// joined = "苹果 | 香蕉 | 橘子"</code></pre><p>Split 和 Join 是一对反操作：Split 拆开，Join 拼回。处理"用分隔符组织的数据"非常方便。</p><h3>任务</h3><p>把 "a-b-c" 用 Split 按 <code>-</code> 拆开，再用 Join 用 <code>+</code> 拼回，输出 <strong>a+b+c</strong></p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        string s = "a-b-c";\n        // 分割再拼接\n    }\n}`, expectedOutput:'a+b+c', hint:'Split(\'-\') 拆开，string.Join("+", arr) 拼回。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        string s = "a-b-c";\n        string[] arr = s.Split('-');\n        string result = string.Join("+", arr);\n        Console.WriteLine(result);\n    }\n}` }
            ]}
        ]
    },
    // ============ 阶段 4：方法与面向对象 ============
    {
        stage: '方法与面向对象', stageDesc: '迈向真正的工程化编程',
        chapters: [
            { id:8, title:'第 8 章：方法', desc:'把代码组织成可复用的块', lessons: [
                { id:'c8l1', title:'定义与调用方法', content:`<h3>方法：可复用的代码块</h3><p>当你发现一段代码要<strong>反复使用</strong>，就把它包成一个方法。方法像一个"技能"：定义一次，随时调用，避免重复写。</p><pre><code>static int Add(int a, int b)\n{\n    return a + b;   // return 把结果返回给调用者\n}\n\nint result = Add(3, 5);  // 调用，result = 8</code></pre><h3>方法签名各部分</h3><ul><li><code>static</code> — 静态方法（Main 里调用其他方法，那个方法必须是 static）</li><li><code>int</code> — 返回值类型（不返回用 <code>void</code>）</li><li><code>Add</code> — 方法名</li><li><code>(int a, int b)</code> — 参数列表（调用时传入）</li></ul><h3>任务</h3><p>定义方法 <code>Multiply(int a, int b)</code> 返回乘积，计算 6×7 输出 <strong>42</strong></p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Console.WriteLine(Multiply(6, 7));\n    }\n    // 定义 Multiply\n}`, expectedOutput:'42', hint:'static int Multiply(int a, int b) { return a * b; }', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Console.WriteLine(Multiply(6, 7));\n    }\n    static int Multiply(int a, int b)\n    {\n        return a * b;\n    }\n}` },
                { id:'c8l2', title:'方法重载', content:`<h3>方法重载：同名不同参</h3><p>同名方法只要<strong>参数类型或个数不同</strong>，就可以并存，这叫<strong>重载</strong>。调用时编译器根据你传的参数自动选对应版本：</p><pre><code>static int Add(int a, int b) { return a + b; }\nstatic double Add(double a, double b) { return a + b; }\n\nAdd(3, 5);       // 调用 int 版，返回 8\nAdd(1.5, 2.0);   // 调用 double 版，返回 3.5</code></pre><p>好处：不用为 int 版和 double 版各起一个名字，调用者只记一个 <code>Add</code> 就行。<strong>重载看的是参数，与返回值类型无关</strong>。</p><h3>任务</h3><p>定义两个 Add：int 版返回 8（3+5），double 版返回 3.5（1.5+2.0）。分别输出：</p><pre><code>8\n3.5</code></pre>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Console.WriteLine(Add(3, 5));\n        Console.WriteLine(Add(1.5, 2.0));\n    }\n    // 两个 Add\n}`, expectedOutput:'8\n3.5', hint:'一个 static int Add(int,int)，一个 static double Add(double,double)。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Console.WriteLine(Add(3, 5));\n        Console.WriteLine(Add(1.5, 2.0));\n    }\n    static int Add(int a, int b) { return a + b; }\n    static double Add(double a, double b) { return a + b; }\n}` },
                { id:'c8l3', title:'递归', content:`<h3>递归：方法调用自己</h3><p>递归是方法<strong>调用自身</strong>的技巧。核心思想：把大问题拆成<strong>同类型的更小问题</strong>，直到小到能直接给出答案。</p><p>以阶乘为例：5! = 5 × 4!，而 4! = 4 × 3!... 一直到 1! = 1（这就是<strong>终止条件</strong>）。</p><pre><code>static int Factorial(int n)\n{\n    if (n &lt;= 1) return 1;          // 终止条件\n    return n * Factorial(n - 1);   // 递归调用\n}\n// Factorial(5) 的执行过程：\n// 5 * Factorial(4)\n//   4 * Factorial(3)\n//     3 * Factorial(2)\n//       2 * Factorial(1) → 返回 1\n//     → 2*1=2 → 3*2=6 → 4*6=24 → 5*24=120</code></pre><p>⚠️ <strong>必须有终止条件</strong>，否则无限递归，程序崩溃。</p><h3>任务</h3><p>用递归实现斐波那契数列：F(1)=1, F(2)=1, F(n)=F(n-1)+F(n-2)。计算 F(7) 输出 <strong>13</strong></p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Console.WriteLine(Fib(7));\n    }\n    // 递归 Fib\n}`, expectedOutput:'13', hint:'if (n <= 2) return 1; return Fib(n-1) + Fib(n-2);', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Console.WriteLine(Fib(7));\n    }\n    static int Fib(int n)\n    {\n        if (n <= 2) return 1;\n        return Fib(n - 1) + Fib(n - 2);\n    }\n}` }
            ]},
            { id:9, title:'第 9 章：类与对象', desc:'面向对象的核心', lessons: [
                { id:'c9l1', title:'创建第一个类', content:`<h3>类与对象：图纸与实物</h3><p><strong>类</strong>是设计图纸，<strong>对象</strong>是按图纸造出来的实体。比如"车"是类，"我的红色车"是对象。一个类可以造出无数个对象。</p><pre><code>class Dog\n{\n    public string Name;  // 字段：存数据\n    public int Age;\n    public void Bark()   // 方法：定义行为\n    {\n        Console.WriteLine(Name + " 汪汪！");\n    }\n}\n\nDog myDog = new Dog();   // 用 new 造一个对象\nmyDog.Name = "旺财";     // 给字段赋值\nmyDog.Bark();             // 调用方法 → 旺财 汪汪！</code></pre><p><code>public</code> 表示"公开可访问"，外部能读写。<code>new 类名()</code> 是创建对象的标准写法。</p><h3>任务</h3><p>定义 Student 类，有 Name 和 Score 字段，Introduce() 方法输出：</p><pre><code>我叫小明，分数是90</code></pre>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Student s = new Student();\n        s.Name = "小明";\n        s.Score = 90;\n        s.Introduce();\n    }\n}\n// 定义 Student 类`, expectedOutput:'我叫小明，分数是90', hint:'public string Name; public int Score; 方法里用插值输出。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Student s = new Student();\n        s.Name = "小明";\n        s.Score = 90;\n        s.Introduce();\n    }\n}\nclass Student\n{\n    public string Name;\n    public int Score;\n    public void Introduce()\n    {\n        Console.WriteLine($"我叫{Name}，分数是{Score}");\n    }\n}` },
                { id:'c9l2', title:'构造函数', content:`<h3>构造函数：创建时自动初始化</h3><p>每次 <code>new</code> 对象后都要手动给字段赋值很麻烦。<strong>构造函数</strong>是与类同名的方法，在 <code>new</code> 时自动调用，可以一次把数据传进去：</p><pre><code>class Point\n{\n    public int X, Y;\n    public Point(int x, int y)  // 构造函数，与类同名\n    {\n        X = x;\n        Y = y;\n    }\n}\n\nPoint p = new Point(3, 4);  // 创建时直接传参\n// p.X = 3, p.Y = 4</code></pre><p>构造函数没有返回值类型（连 void 都没有），名字必须和类名完全一样。</p><h3>任务</h3><p>定义 Book 类，构造函数接收 title 和 price，Info() 方法输出：</p><pre><code>《C#入门》售价 59 元</code></pre>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Book b = new Book("C#入门", 59);\n        b.Info();\n    }\n}\n// Book 类`, expectedOutput:'《C#入门》售价 59 元', hint:'构造函数 public Book(string title, int price)，赋值给字段。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Book b = new Book("C#入门", 59);\n        b.Info();\n    }\n}\nclass Book\n{\n    public string Title;\n    public int Price;\n    public Book(string title, int price)\n    {\n        Title = title;\n        Price = price;\n    }\n    public void Info()\n    {\n        Console.WriteLine($"《{Title}》售价 {Price} 元");\n    }\n}` }
            ]}
        ]
    },
    // ============ 阶段 5：进阶特性 ============
    {
        stage: '进阶特性', stageDesc: '面向对象进阶与高级语法',
        chapters: [
            { id:10, title:'第 10 章：继承与多态', desc:'代码复用的精髓', lessons: [
                { id:'c10l1', title:'继承基础', content:`<h3>继承：子类复用父类代码</h3><p>继承让子类<strong>自动拥有</strong>父类的所有字段和方法，避免重复写同样的代码。用 <code>:</code> 表示继承关系。</p><pre><code>class Animal\n{\n    public string Name;\n    public void Eat() { Console.WriteLine(Name + " 在吃"); }\n}\nclass Dog : Animal  // Dog 继承 Animal\n{\n    public void Bark() { Console.WriteLine(Name + " 汪汪"); }\n}\n\nDog d = new Dog();\nd.Name = "旺财";  // Dog 自动有了 Name 字段\nd.Eat();          // 也自动有了 Eat 方法\nd.Bark();</code></pre><p>继承表达"<strong>是一个</strong>"关系：Dog <strong>是</strong>一个 Animal，所以继承合理。</p><h3>任务</h3><p>定义 Shape 类有 Name 字段，Circle 继承它并新增 Radius 字段和 Area() 方法，输出 "圆形面积是 12.56"</p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Circle c = new Circle();\n        c.Name = "圆形";\n        c.Radius = 2;\n        c.Area();\n    }\n}\n// Shape 和 Circle 类`, expectedOutput:'圆形面积是 12.56', hint:'Circle : Shape，Area 里用 3.14 * Radius * Radius。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Circle c = new Circle();\n        c.Name = "圆形";\n        c.Radius = 2;\n        c.Area();\n    }\n}\nclass Shape\n{\n    public string Name;\n}\nclass Circle : Shape\n{\n    public double Radius;\n    public void Area()\n    {\n        Console.WriteLine($"{Name}面积是 {3.14 * Radius * Radius}");\n    }\n}` },
                { id:'c10l2', title:'virtual 与 override', content:`<h3>多态：同一调用，不同行为</h3><p>父类用 <code>virtual</code> 标记一个方法"可以被改写"，子类用 <code>override</code> 实际改写它。这样<strong>同样的调用，不同对象表现出不同行为</strong>——这就是多态。</p><pre><code>class Animal\n{\n    public virtual void Speak() { Console.WriteLine("动物发声"); }\n}\nclass Cat : Animal\n{\n    public override void Speak() { Console.WriteLine("喵"); }\n}\nclass Dog : Animal\n{\n    public override void Speak() { Console.WriteLine("汪汪"); }\n}</code></pre><p>为什么需要多态？因为你可以用父类变量统一管理所有子类：<code>Animal a = new Dog(); a.Speak();</code> 输出"汪汪"——编译时是 Animal，运行时却执行 Dog 的版本。这是大型软件灵活性的根基。</p><h3>任务</h3><p>Animal 的 Speak 输出 "动物发声"，Dog 重写输出 "汪汪"。创建 Dog 调用 Speak，输出 <strong>汪汪</strong></p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Dog d = new Dog();\n        d.Speak();\n    }\n}\n// Animal 和 Dog`, expectedOutput:'汪汪', hint:'父类方法用 virtual，子类用 override。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Dog d = new Dog();\n        d.Speak();\n    }\n}\nclass Animal\n{\n    public virtual void Speak() { Console.WriteLine("动物发声"); }\n}\nclass Dog : Animal\n{\n    public override void Speak() { Console.WriteLine("汪汪"); }\n}` }
            ]},
            { id:11, title:'第 11 章：接口', desc:'定义契约', lessons: [
                { id:'c11l1', title:'接口入门', content:`<h3>接口：定义"能做什么"的契约</h3><p>接口是一组方法的<strong>声明</strong>（只写方法名和参数，不写实现）。它规定了"能做什么"，但<strong>不关心怎么做</strong>。类实现接口时，必须提供所有方法的具体实现。</p><pre><code>interface IShape\n{\n    double GetArea();  // 只声明，不实现\n}\nclass Circle : IShape\n{\n    public double R;\n    public double GetArea() { return 3.14 * R * R; }  // 必须实现\n}</code></pre><p>接口名字习惯以 <code>I</code> 开头（IShape、IComparable）。它和继承不同：继承是"是什么"，接口是"能做什么"。一个类只能继承一个父类，但可以<strong>实现多个接口</strong>。</p><h3>任务</h3><p>定义 IPlayable 接口有 Play()，Guitar 类实现它，调用输出 <strong>弹吉他</strong></p>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Guitar g = new Guitar();\n        g.Play();\n    }\n}\n// IPlayable 和 Guitar`, expectedOutput:'弹吉他', hint:'interface IPlayable { void Play(); }，Guitar : IPlayable { public void Play() {...} }', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Guitar g = new Guitar();\n        g.Play();\n    }\n}\ninterface IPlayable\n{\n    void Play();\n}\nclass Guitar : IPlayable\n{\n    public void Play() { Console.WriteLine("弹吉他"); }\n}` }
            ]},
            { id:12, title:'第 12 章：集合与泛型', desc:'List / Dictionary', lessons: [
                { id:'c12l1', title:'List 动态列表', content:`<h3>List：长度可变的数组</h3><p>数组创建后长度就固定了，<code>List</code> 则可以<strong>随时增删</strong>元素，更灵活。用泛型 <code>List&lt;int&gt;</code> 指定存什么类型。</p><pre><code>List&lt;int&gt; nums = new List&lt;int&gt;();\nnums.Add(1);    // 添加元素\nnums.Add(2);\nnums.Add(3);\nConsole.WriteLine(nums.Count);  // 3（元素个数，类似数组的 Length）\nforeach (int n in nums) Console.WriteLine(n);</code></pre><p>数组用 <code>.Length</code>，List 用 <code>.Count</code>——这点容易混淆，记住：List 是"数一下有多少个"用 Count。</p><h3>任务</h3><p>用 List 存储 10、20、30，输出它们的和 <strong>60</strong></p>`, starterCode:`using System;\nusing System.Collections.Generic;\n\nclass Program\n{\n    static void Main()\n    {\n        // List 操作\n    }\n}`, expectedOutput:'60', hint:'List<int> nums = new List<int>(); 加 10、20、30，foreach 累加。', answer:`using System;\nusing System.Collections.Generic;\n\nclass Program\n{\n    static void Main()\n    {\n        List<int> nums = new List<int>();\n        nums.Add(10);\n        nums.Add(20);\n        nums.Add(30);\n        int sum = 0;\n        foreach (int n in nums) sum += n;\n        Console.WriteLine(sum);\n    }\n}` }
            ]}
        ]
    },
    // ============ 阶段 6：实战项目 ============
    {
        stage: '实战项目', stageDesc: '综合运用所学，做出真正的东西',
        chapters: [
            { id:13, title:'第 13 章：综合实战', desc:'把所有知识串起来', lessons: [
                { id:'c13l1', title:'实战：简易计算器', content:`<h3>实战：简易计算器</h3><p>把前面学的<strong>方法 + switch + 字符串返回</strong>串起来，做一个真正有用的程序。要点：根据运算符返回结果，除法要处理除数为 0 的情况。</p><h3>任务</h3><p>实现 <code>Calculate(double a, double b, string op)</code> 方法，调用 Calculate(10, 3, "+") 和 Calculate(10, 0, "/")，输出：</p><pre><code>10 + 3 = 13\n错误：除数不能为 0</code></pre>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Console.WriteLine($"10 + 3 = {Calculate(10, 3, "+")}");\n        Console.WriteLine(Calculate(10, 0, "/"));\n    }\n    static string Calculate(double a, double b, string op)\n    {\n        // 实现\n        return "";\n    }\n}`, expectedOutput:'10 + 3 = 13\n错误：除数不能为 0', hint:'switch 处理 op，除法时 if (b == 0) 返回错误信息。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Console.WriteLine($"10 + 3 = {Calculate(10, 3, "+")}");\n        Console.WriteLine(Calculate(10, 0, "/"));\n    }\n    static string Calculate(double a, double b, string op)\n    {\n        switch (op)\n        {\n            case "+": return (a + b).ToString();\n            case "-": return (a - b).ToString();\n            case "*": return (a * b).ToString();\n            case "/":\n                if (b == 0) return "错误：除数不能为 0";\n                return (a / b).ToString();\n            default: return "不支持的运算符";\n        }\n    }\n}` },
                { id:'c13l2', title:'实战：猜数字游戏', content:`<h3>实战：猜数字游戏</h3><p>游戏的经典逻辑：<strong>玩家猜数，程序给提示</strong>。用循环 + 条件判断就能实现。这是理解游戏 AI、反馈系统的基础。</p><h3>任务</h3><p>目标数 42，玩家依次猜 30、50、42。遍历 guesses 数组，每次比较并给出"太小了/太大了/猜对了"：</p><pre><code>猜 30：太小了\n猜 50：太大了\n猜 42：猜对了！</code></pre>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int target = 42;\n        int[] guesses = { 30, 50, 42 };\n        // 模拟猜测\n    }\n}`, expectedOutput:'猜 30：太小了\n猜 50：太大了\n猜 42：猜对了！', hint:'foreach 遍历 guesses，if 判断与 target 关系。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        int target = 42;\n        int[] guesses = { 30, 50, 42 };\n        foreach (int g in guesses)\n        {\n            if (g < target) Console.WriteLine($"猜 {g}：太小了");\n            else if (g > target) Console.WriteLine($"猜 {g}：太大了");\n            else Console.WriteLine($"猜 {g}：猜对了！");\n        }\n    }\n}` },
                { id:'c13l3', title:'实战：学生管理系统', content:`<h3>终极实战：学生管理系统</h3><p>把<strong>类 + 数组 + 遍历找极值</strong>组合起来，模拟真实项目的数据管理。这是后端开发、CRUD 系统的最小雏形。</p><h3>任务</h3><p>创建 3 个学生：张三85、李四92、王五78。用 Student 数组存储，遍历找出最高分学生，输出：</p><pre><code>最高分：李四 92分</code></pre>`, starterCode:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        // 学生管理\n    }\n}\nclass Student\n{\n    public string Name;\n    public int Score;\n}`, expectedOutput:'最高分：李四 92分', hint:'Student[] 存 3 个，遍历找 Score 最大的。', answer:`using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Student[] students = new Student[3];\n        students[0] = new Student { Name = "张三", Score = 85 };\n        students[1] = new Student { Name = "李四", Score = 92 };\n        students[2] = new Student { Name = "王五", Score = 78 };\n        Student best = students[0];\n        foreach (Student s in students)\n            if (s.Score > best.Score) best = s;\n        Console.WriteLine($"最高分：{best.Name} {best.Score}分");\n    }\n}\nclass Student\n{\n    public string Name;\n    public int Score;\n}` }
            ]}
        ]
    }
];

function getTotalLessons() { let n=0; CHAPTERS_DATA.forEach(s=>s.chapters.forEach(c=>n+=c.lessons.length)); return n; }
function findLesson(id) { for(const s of CHAPTERS_DATA) for(const c of s.chapters) for(const l of c.lessons) if(l.id===id) return {lesson:l,chapter:c,stage:s}; return null; }
function findChapter(id) { for(const s of CHAPTERS_DATA) for(const c of s.chapters) if(c.id===id) return {chapter:c,stage:s}; return null; }
function getAllLessonsFlat() { const list=[]; CHAPTERS_DATA.forEach(s=>s.chapters.forEach(c=>c.lessons.forEach(l=>{list.push({id:l.id,title:l.title,lesson:l,chapter:c,stage:s})}))); return list; }
